mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
# urlpatterns = ('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    # url(r'^polls/', include('polls.urls')),
    # url(r'^polls/', include('polls.urls')),
    url(r'^admin/', include(admin.site.urls)),
]
# )

polls/urls.py
from django.conf.urls import url

from . import views

# Django uses URLconfs -- this maps URL patterns to views

# add this so that if some models have also an index page, Django doesn't get confused as to which index page these urls refer to. Adding app_name ensures that we're calling the index in the polls/views.py
app_name = 'polls'
urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    # /polls/
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /polls/5/
    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /polls/5/results/
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # pass in pk instead of question_id when using generic in views
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # /polls/5/vote/
    # browser will run detail() method and display whatever ID you provide in the results
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible #necessary so that in python shell get helpful results back from Question.objects.all()
from django.utils import timezone
# Create your models here.

class Poll(models.Model):
        name = models.CharField(max_length=200)
        taken = models.IntegerField(default=0)
        def __str__(self):
             return self.name

DEFAULT_POLL_ID = 1
# Question has 2 fields
class Question(models.Model):
        poll = models.ForeignKey(Poll, on_delete=models.CASCADE, default=DEFAULT_POLL_ID)
        # CharField has required arg of max_length
        question_text = models.CharField(max_length=200)
        pub_date = models.DateTimeField('date published')
        def __str__(self):
            return self.question_text
        def was_published_recently(self):
            return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

# Choice has 3 fields
class Choice(models.Model):
        question = models.ForeignKey(Question, on_delete=models.CASCADE)
        choice_text = models.CharField(max_length=200)
        # Field can have optional arguments
        votes = models.IntegerField(default=0)
        def __str__(self):
            return self.choice_text

DEFAULT_USER_ID = 1
# Following this tutorial:
# https://djangogirls.gitbooks.io/django-girls-tutorial-extensions/homework_create_more_models/
class Comment(models.Model):
        question = models.ForeignKey(Question, on_delete=models.CASCADE)
        author = models.CharField(max_length=200)
        text = models.TextField()
        created_date = models.DateTimeField(default=timezone.now)
        approved_comment = models.BooleanField(default=False) 
        # user = models.OneToOneField(User, on_delete=models.CASCADE, default=DEFAULT_USER_ID)
        user = models.ForeignKey(User, on_delete=models.CASCADE, default=DEFAULT_USER_ID)

        def approve(self):
            self.approved_comment = True
            self.save()

        def __str__(self):
            return self.text


class PollComment(models.Model):
        poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
        author = models.CharField(max_length=200)
        text = models.TextField()
        created_date = models.DateTimeField(default=timezone.now)
        approved_comment = models.BooleanField(default=False) 
        # user = models.OneToOneField(User, on_delete=models.CASCADE, default=DEFAULT_USER_ID)
        user = models.ForeignKey(User, on_delete=models.CASCADE, default=DEFAULT_USER_ID)

        def approve(self):
            self.approved_comment = True
            self.save()

        def __str__(self):
            return self.text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
# from django.urls import reverse
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def home(request):
    return render(request, 'home.html')

# def index(request):
    #### return HttpResponse("Hello, world. You're at the polls index.")
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
    ## template = loader.get_template('polls/index.html')
    ### output = ', '.join([q.question_text for q in latest_question_list])
#     context = { 'latest_question_list': latest_question_list, }
    ### return HttpResponse(output)
    ## below is the long way to do render
    ## return HttpResponse(template.render(context, request))
    # render() takes request obejct as first arg, template name as 2nd arg, and a dictionary as its option third arg 
    # return render(request, 'polls/index.html', context)


# def detail(request, question_id):
    #### return HttpResponse("You're looking at question %s." % question_id)
    ##try: 
    ##    question = Question.objects.get(pk=question_id)
    ##except Question.DoesNotExist:
    ##    # if the question id does not exist,  an Http404 exception is raised
    ##    raise Http404("Question does not exist")
    # question = get_object_or_404(Question, pk=question_id)
    # return render(request, 'polls/detail.html', {'question': question})


# def results(request, question_id):
    # response = "You're looking at the results of question %s."
    # question = get_object_or_404(Question, pk=question_id)
    # return HttpResponse(response % question_id)
    # return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    # return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        # request.POST allows you to access submitted data by key name
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        # key error is raised if 'choice' does not exist
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/detail.html', { 'question': question, 'error_message': "You didn't select a choice.", })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # always return an HttpResponseRedirect after successfully dealing with
        # POST data. This prevents data from being posted twice if a user hits
        # the Back button
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- http://django-bootstrap3.readthedocs.io/en/latest/quickstart.html -->

{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!--div class="navbar-header">
      <a class="navbar-brand" href="#">Polls</a>
    </div-->
    <ul class="nav navbar-nav">
      <li><a href="{% url 'polls:home' %}">Home</a></li>
      <li><a href="{% url 'polls:index' %}">Polls</a></li>
			<li><a href="#">Page 1</a></li>
			<li><a href="#">Page 2</a></li>
			<li><a href="#">Page 3</a></li>
    </ul>
  </div>
</nav>


{% block content %}
{% endblock content %}

polls/templates/home.html
{% extends "base.html" %}

{% block content %}
{% load staticfiles %}



{% endblock content %}

polls/templates/polls/detail.html
{% extends "base.html" %}

{% block content %}
{% load staticfiles %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<!-- set the forms action to polls:vote with the question id and set the method as post -->
<form action="{% url 'polls:vote' question.id %}" method="post">
	<!-- takes care of the Cross Site Request Forgeries -->
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
	<!-- value of each radio button is the question id so that's what's sent in the POST data 
	forloop.counter indicates the number of times for tag has gone through its loop -->
				<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
				<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
	{% endfor %}
	<input type="submit" value="Vote" />
</form>


<a href="{% url 'polls:index' %}">Return to Polls</a><br>


<!--ul>
% for choice in question.choice_set.all %}
	<li>{ choice.choice_text }}</li>
% endfor %}
</ul-->

{% endblock content %}

polls/templates/polls/index.html
{% extends "base.html" %}

{% block content %}
{% load staticfiles %}
<!--% load bootstrap3 %}

% bootstrap_css %}
% bootstrap_javascript %}

% bootstrap_messages %-->

<h1>Polls</h1>

{% if latest_question_list %}
	<ul>
			{% for question in latest_question_list %}
				<!-- below is hardcorded url -->
				<!--li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li-->
				<!-- below is for when app_name is omitted from urls.py -->
				<!--li><a href="% url 'detail' question.id %}">{{ question.question_text }}</a></li-->
				<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
				{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}


{% endblock content %}

polls/templates/polls/results.html
{% extends "base.html" %}

{% block content %}
{% load staticfiles %}

<h1>{{ question.question_text }}</h1>

<ul>
		{% for choice in question.choice_set.all %}
			<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
		{% endfor %}
</ul>

<a href="{% url 'polls:index' %}">Return to Polls</a><br>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock content %}